language: python

# added by kr
env:
  global:
    - CPLUS_INCLUDE_PATH=/usr/include/gdal
    - C_INCLUDE_PATH=/usr/include/gdal

# command to install dependencies
python:
  - 3.7
  
# added by kr
before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ppa
  - sudo apt-get -qq update
  - sudo apt-get -qq install libgdal-dev gdal-bin
  
install:
  - pip install -r requirements.txt
  - pip install gdal==`gdal-config --version`

before_script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py collectstatic --noinput

script:
  - black --check .
  - flake8 .
  - coverage run --source=accessible_restaurant manage.py test

after_script:
  - coveralls
